#!/bin/bash
set -e
set -o pipefail
case "$1" in
	configure|install|upgrade) 
		su "$(users)" -c '/usr/bin/pip3 install --upgrade pynput'
		su "$(users)" -c '/usr/bin/pip3 install --upgrade inputs';;
	abort-upgrade|abort-deconfigure|abort-remove) ;;
	*) echo -e "\nERROR: CALLED WITH UNKNOWN ARGUMENT $1\n"; exit 2 ;;
esac
	
